version: '3'

services:
  dns:
    image: coredns/coredns
    command: -conf /dns.cfg
    volumes:
      - ./dns.cfg:/dns.cfg
    depends_on:
      - etcd
  etcd:
    image: quay.io/coreos/etcd:v2.3.8
    command: -listen-client-urls "http://0.0.0.0:2379,http://0.0.0.0:4001" -advertise-client-urls "http://etcd:2379,http://etcd:4001"
    expose:
      - "2379"
      - "4001"
  bash:
    image: debian:jessie
    command: sleep infinity
