version: '3'

services:
  openvpn-server:
    build:
      context: ./
      dockerfile: Dockerfile
    cap_add:
     - NET_ADMIN
    restart: always
    depends_on:
      - etcd
      - dns
    ports:
     - "1194:1194/udp"
    volumes:
      - ovpn-data:/etc/openvpn
    networks:
      - vpn_net

  dns:
    image: coredns/coredns
    command: -conf /dns.cfg
    volumes:
      - ./dns.cfg:/dns.cfg
    depends_on:
      - etcd
    expose:
      - "53/tcp"
      - "53/udp"
    networks:
      vpn_net:
        ipv4_address: 172.16.238.254

  etcd:
    image: quay.io/coreos/etcd:v2.3.8
    command:
      - -listen-client-urls
      - "http://0.0.0.0:2379,http://0.0.0.0:4001"
      - -advertise-client-urls
      - "http://etcd:2379,http://etcd:4001"
    expose:
      - "2379"
      - "4001"
    networks:
      - vpn_net

volumes:
  ovpn-data:
    external: true

networks:
  vpn_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
